/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff, 0xf8b65139, 0xf1a1bf37, 0xeac0c6e6, 0xe411f039, 0xdd93cdd6,
        0xd744fcc9, 0xd124243d, 0xcb2ff529, 0xc5672a10, 0xbfc886ba, 0xba52d7ee,
        0xb504f333, 0xafddb68e, 0xaadc0846, 0xa5fed6a9, 0xa14517cb, 0x9cadc957,
        0x9837f050, 0x93e298df, 0x8facd61d, 0x8b95c1e3, 0x879c7c96, 0x83c02cf9,
};

#define LOAD_AVG_PERIOD 24
#define LOAD_AVG_MAX 35936